# Generated by Django 5.1.7 on 2025-07-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('origin', models.CharField(max_length=255, verbose_name='Dirección de recogida')),
                ('destination', models.CharField(max_length=255, verbose_name='Dirección de destino')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('time', models.CharField(choices=[('morning', 'Morning (8AM - 12PM)'), ('afternoon', 'Afternoon (12PM - 4PM)'), ('evening', 'Evening (4PM - 8PM)')], max_length=50, verbose_name='Hora preferida')),
                ('date', models.DateField(verbose_name='Fecha de mudanza')),
                ('size', models.CharField(choices=[('studio', 'Studio Apartment'), ('1bed', '1-Bedroom'), ('2bed', '2-Bedroom'), ('3bed', '3-Bedroom'), ('4bed', '4-Bedroom+')], max_length=50, verbose_name='Tamaño de la vivienda')),
                ('helpers', models.PositiveIntegerField(verbose_name='Número de ayudantes')),
                ('special_item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artículos especiales')),
            ],
        ),
    ]
