# Generated by Django 5.1.7 on 2025-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_cachedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distancia (millas)'),
        ),
    ]
