# Generated by Django 5.1.7 on 2025-07-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_contact_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='distance',
        ),
    ]
